### ISSUE TITLE
Issues with the current deployment process

### ISSUE THREAD

**Issue by baetheus** [planetscale/cli#254]
The current production deployment process advises wrapping an existing application or executable in the pscale client. This becomes problematic for the following reasons:

1. Not all existing apps are keyed to look for the `DATABASE_URL` env variable in their configurations.
2. Not all existing apps are directly managed (some are packaged upstream and are pulled into the same pod as the application) and so require repackaging to wrap in the pscale binary.
3. For larger scale deployments where processing cycles or space are in short supply, running an extra 9Mb process alongside each application could be a non-starter.
4. For other, uptime sensitive deployments, running the primary application as a sub-process of pscale could be a non-starter.

It is with these problems in mind that I request a standalone container image blessed by planetscale that takes the following env vars:

```
PLANETSCALE_ORG: <ORG_NAME>
PLANETSCALE_SERVICE_TOKEN_NAME: <SERVICE_TOKEN_NAME>
PLANETSCALE_SERVICE_TOKEN: <SERVICE_TOKEN>
PLANETSCALE_PORT: <EXPOSED_PORT>
PLANETSCALE_DATABASE: <DATABASE_NAME>
PLANETSCALE_BRANCH: <DATABASE_BRANCH>
```

And exposes the resulting forwarding service on `PLANESCALE_PORT`. This would solve all four of the problems outlined above and is in fact what I ended up deploying to test planetscale. I hope this helps, I'm looking forward to playing with your product.

**Comment by nickvanw** [comment]
Hey @baetheus!

This lines up with something that we've been looking to produce indeed - the [sidecar pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar) is very common, and something that PlanetScale's CLI can easily do inside of a separate container from an application. 

I can't give an exact ETA, but this is high up on the list of libraries and tools that we want to provide to make it easier for people to use PlanetScale in their applications.

**Comment by fatih** [comment]
Hi folks. I created a simple PR to kickstart the conversation: https://github.com/planetscale/cli/pull/280

`pscale connect` will probably only work if you expose 3306 to host 3306. I've added more details on the PR itself for our upcoming plans. We might expose the sidecar container as part of the https://github.com/planetscale/sql-proxy repository. 


> And exposes the resulting forwarding service on PLANESCALE_PORT

Can `docker` expose a port of a container to the host it's running? Or do you run your application in Kubernetes or similar environments?

**Comment by baetheus** [comment]
> Can docker expose a port of a container to the host it's running? Or do you run your application in Kubernetes or similar environments?

I use both docker and kubernetes. Docker can bind a container port to a host port with something like `docker run -p 33044:3306 -i -t PLANETSCALE_DOCKER_IMAGE` if running locally. In more complicated docker compose setups docker can allow containers to talk to each directly via their container ips, in which case a simple `--expose 3306` via the docker command or an `EXPOSE 3306` in the planetscale docker image Dockerfile would suffice.

Kubernetes has similar (albeit more powerful) controls for exposing the ports of a container or pod(group of containers sharing cpu/memory/net/storage resources). However, as a sidecar it might make more sense to allow communication with planetscale over a unix socket than a network socket.

**Comment by fatih** [comment]
Hi @baetheus 

We released two new containers that will make it easy for containerized apps to use as a sidecar. You can get them via these commands:

```
# pscale CLI
docker pull planetscale/pscale:latest
docker pull planetscale/pscale:v0.43.0

# pscale-proxy sidecar
docker pull planetscale/pscale-proxy:latest
docker pull planetscale/pscale-proxy:v0.6.0
```

* The first container (`planetscale/pscale`) wraps the CLI with the required dependencies so you can run all the CLI commands, such as quickly opening a  MySQL shell. This container can also be useful to integrate with CI/CD systems to create a test database branch, run the tests and then delete the branch.
* The second container (`planetscale/pscale-proxy`) is a standalone proxy that opens a secure connection to your database. It's the same as if you would call `pscale connect`.

Because the CLI is more extensive in terms of functionality and dependencies, the image size is larger:

```
planetscale/pscale         latest    73fae4e6a02c   19 hours ago   50.1MB
planetscale/pscale-proxy   latest    aa949532c7e1   17 hours ago   11.6MB
```

--- 

For this issue, we're interested in how to open a secure connection to our database.[ I added a section](https://github.com/planetscale/sql-proxy#using-the-docker-container) to the `planetscale/sql-proxy` repository that shows an example:

```
$ docker run -p 127.0.0.1:3306:3306 planetscale/pscale-proxy \
  --host 0.0.0.0 \
  --org "$PLANETSCALE_ORG" \
  --database "$PLANETSCALE_DATABASE" \
  --branch "$PLANETSCALE_BRANCH" \
  --service-token "$PLANETSCALE_SERVICE_TOKEN" \
  --service-token-name "$PLANETSCALE_SERVICE_TOKEN_NAME" 
```

This command will map the container port `3306` to your host address `127.0.0.1:3306`. Let me know if you can have a look at this sidecar. If you're using Kubernetes, please also let me know if you see any issues or if there are things that can be better.

> However, as a sidecar, it might make more sense to allow communication with planetscale over a UNIX socket than a network socket.

That's something on our roadmap, and I agree that it would be helpful. Though for a UNIX socket, if you're aiming to deploy to a Kubernetes cluster, you also need to create an `emptyDir` volume and mount the volume to each container. That's slightly more work involved compared to TCP, but I think it would be more performant. We can add examples to our Readme on how to deploy it to Kubernetes. But first, let's make sure the sidecar is working well and there are no significant issues.

Thanks again for the feedback.

**Comment by fatih** [comment]
I'm closing this issue as the images a released now. Please let's open an issue from now on for specific feedbacks or problems we see while using the images.
