### ISSUE TITLE
Release Naming Scheme makes it impossible to pull latest

### ISSUE THREAD

**Issue by Anders-PlanetScale** [planetscale/cli#279]
The way we are currently naming pscale packages each release is not done in a way that would allow someone to write code to pull whatever the latest version of say pscale_linux_386.deb. The package names all have the version number in the name and thus are all unique.

If we kept the package names the same across releases and just changed the release tag then we should be able to always get the latest version of the package using something like;

`wget https://github.com/planetscale/cli/releases/latest/pscale_linux_386.deb`

If we want people to build Docker images or sidecar containers we should make it easy for them to pull the latest version of pscale, without having to update their dockerfile each new release.

**Comment by fatih** [comment]
Hi Anders, 

I like the suggestion. I opened a [proof of concept branch](https://github.com/planetscale/cli/compare/fatih-simplify-archive-name?expand=1) that implements this suggestion. 

However, I'm not sure it's the best way to move forward. We're losing the ability to know which version the downloaded CLI archive is. The user has to run the CLI with `pscale version` to see it, which is a step backward. It's also not user-friendly, because maybe the user is scripting for a Linux OS but is using macOS.

I believe the better way is to use GitHub's API to get the latest version and use that for scripting. Here is a pseudo-code example of doing it with `jq` (there are many other ways to do it, check out this page for more example: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c) :


```
version=$( curl --silent "https://api.github.com/repos/planetscale/cli/releases/latest" |  jq -r .tag_name)
wget https://github.com/planetscale/cli/releases/download/${version}/pscale_${version:1}_linux_386.deb
```

I also checked other CLI's such as GitHub's `gh` or DigitalOcean's `doctl`, they also include the version name in the file path.

**Comment by fatih** [comment]
We provide now [container images](https://github.com/planetscale/cli#container-images) that points to the latest version:

```
docker pull planetscale/pscale:latest
```

I'm closing this issue as I think the current state is OK and preferable. Feel free to reopen if you think it can be improved or things are not clear.
