### ISSUE TITLE
Allow setting env var different than `DATABASE_URL`

### ISSUE THREAD

**Issue by janpio** [planetscale/cli#322]
`DATABASE_URL` is a good default assumption for `connect --execute`, but sometimes it would be hand to be able to define a different ENV var name es the application is already using a different one, similar to `--execute-protocol 'mysql'`.

I suggest `--execute-env` so this becomes possible: `--execute-env 'PLANETSCALE_DB_URL'`.

**Comment by fatih** [comment]
Hi @janpio 

I assume you want this feature because you're running `pscale connect` already, and want to run another instance of `pscale connect`? If that is the case, each shell will have its own context, and there shouldn't be a conflict. It would be great if you could give more details on how you plan to use this feature.

Another question, wouldn't you also want to change these environment variables?:

```
PLANETSCALE_DATABASE_HOST
PLANETSCALE_DATABASE_NAME
PLANETSCALE_BRANCH_NAME
```

**Comment by janpio** [comment]
Hey, I did not think about that use case yet to run multiple instances of `pscale connect` - but then I would indeed possibly want to be able to adapt most env vars.

My actual use case is that I have a project that already uses another env var, in my example `PLANETSCALE_DB_URL`, that I can not easily change in the application. So being able to use another env var name, would let me set that to `PLANETSCALE_DB_URL` in the command instead of having to mess with the application.

**Comment by fatih** [comment]
Gotcha 👍🏼 , I added it with https://github.com/planetscale/cli/pull/326. We can later improve the functionality.

**Comment by fatih** [comment]
This is now released with the version: https://github.com/planetscale/cli/releases/tag/v0.53.0

**Comment by janpio** [comment]
And works perfectly in our CI: https://github.com/prisma/e2e-tests/pull/1899/checks?check_run_id=3019245240#step:5:136 Thanks!
