### ISSUE TITLE
Add custom connection string for Vercel

### ISSUE THREAD

**Issue by heymartinadams** [planetscale/cli#383]
Sorry, I didn’t see a [PlanetScale.com](https://planetscale.com) repo, so adding this suggestion here:

For [Vercel](https://vercel.com), the certificate string is different, so I would propose adding an option in the dropdown for Vercel as well.

<img width="379" alt="CleanShot 2021-09-01 at 09 26 19@2x" src="https://user-images.githubusercontent.com/11673745/131708357-2353e0a4-a8fa-45df-9d50-828518fea423.png">

For Vercel it’s:
`?sslmode=require&sslcert=/etc/pki/tls/certs/ca-bundle.crt`

**Comment by janpio** [comment]
Are you using Prisma when you experience this? Then this is because Vercel is a different operating system (see the "certificate validation settings" link below box) than the default. 

Buuuut this requirement will go away with the next Prisma version - using `?sslaccept=strict` will be enough, no more different conn strings per operating system. (You can already test that with the `dev` version of Prisma)

**Comment by heymartinadams** [comment]
Oh cool @janpio! 🎉 Yes, was using [Prisma](https://prisma.io) (of course 😄).
