### ISSUE TITLE
pscale CLI on Windows [pscale auth login] error

### ISSUE THREAD

**Issue by YBouz** [planetscale/cli#423]
![image](https://user-images.githubusercontent.com/17670771/139682894-f23d73cb-b157-472f-99a2-0e1375ae3b5c.png)
Installed the pscale cli, and getting a blank error when executing 'pscale auth login'

**Comment by dislick** [comment]
I'm getting the same error on macOS, tried version 0.85.0 and 0.84.0.

```
$ pscale auth login
Error:

```

**Comment by nickvanw** [comment]
Hey all! 

Sorry about this - this was due to a misconfiguration in one of our backend systems, and is unrelated to the CLI itself. 

The fixed for this has been deployed, and I've tested this as working. I'm going to close this out now, but if there are any other issues, don't hesitate to drop a comment.
