### ISSUE TITLE
[Feature Request] Wait for branches to be ready rather than exiting when connecting

### ISSUE THREAD

**Issue by alii** [planetscale/cli#477]
Hey everyone! It would be absolutely superb if the CLI would wait for branches to be ready rather than exiting completely in the following scenario:
![image](https://user-images.githubusercontent.com/25351731/160484087-3d0ae498-596a-443e-acac-474e72211934.png)

**Comment by brianlovin** [comment]
Adding my +1 to this issue — I'm finding myself losing focus and flow because the state of a branch being created is unpredictable, which requires randomly retrying the `connect` command over and over. Some kind of waiting state on the `branch create` call would make it a lot more clear what PlanetScale is doing and inform when it's ready for me to develop against. Thanks!
