### ISSUE TITLE
Restore dump into existing branch

### ISSUE THREAD

**Issue by aaacafe786** [planetscale/cli#538]
i have run the command "pscale database dump <DATABASE_NAME> <BRANCH_NAME>" which created a dump in the root of my project. after that I attempted to run the command "pscale database restore-dump <DATABASE_NAME> <BRANCH_NAME> --dir {dump}"

this gives me the following error message:
![image](https://user-images.githubusercontent.com/102602405/181580433-0c97753e-2257-44e1-967e-78841458897d.png)

am I doing this correctly or this there another way to import data beetween branches?

**Comment by orware** [comment]
Hello @aaacafe786,

Thank you for your issue report! We've had an internal discussion about this and a fix for the situation will be tackled by the team in the near future for it, but in the meantime here is a quick solution that you can utilize.

In the folder that was created by the `dump` command for you, for each table in your database you should see a schema related file ending in `-schema.sql `.

For example:
```
<DATABASE_NAME>.<TABLE_NAME>-schema.sql 
```

In each of those files you will see a regular `CREATE TABLE` entry like this:

```
CREATE TABLE `<TABLE_NAME>` (
    ...
)
```

You should be able to tweak those files and add in the `IF NOT EXISTS` clause to each of them:
```
CREATE TABLE IF NOT EXISTS `<TABLE_NAME>` (
    ...
)
```
After adding the extra `IF NOT EXISTS` to each of those schema files and saving the changes, you should be able to retry your `restore-dump` command again afterward and it should be successful in restoring the data into the new development branch.

---

The reason for the issue itself is because when you create a new branch in a PlanetScale database, it starts off with the same schema from your `main` branch. So, if you attempt to restore a dump into a new branch those tables technically already exist, so the `IF NOT EXISTS` clause helps avoid attempting to recreate them again, which is what was happening when you encountered the error you shared.

**Comment by orware** [comment]
@aaacafe786,

A fix for the situation has already been made in the following [pull request](https://github.com/planetscale/cli/pull/539) thanks to @nickvanw :tada:!

A new v0.112.0 release of the `pscale` CLI should be available now for you to update to and now includes a new parameter to add in when using the `restore-dump` command:

```
--overwrite-tables
```

Adding this option do something similar to the `IF NOT EXISTS` suggestion provided above. Essentially it will `DROP` the existing tables in your development branch, and then recreate them using the `CREATE TABLE` statements in those `*-schema.sql` files that are already present, which achieves the same results, since the tables in your development branch are already empty to start off with.

**Comment by aaacafe786** [comment]
Dear Omar,

thank you for such a swift resolution to my problem!

the following closed PR (https://github.com/jonico/pscale-workflow-helper-scripts/issues/22) illustrates the syntax I have used to access my connection string within the Dockerfile.

It appears to be working, but there is a planetscale-admin issue when I deploy the app

I closed the first issue because it appeared to be connecting and opened a second issue on the cli board: https://github.com/planetscale/cli/issues/541

Thanks again for all your help, that should leave only one more request to work  on

  1.  apply changes to the production database when a pull request is closed
     *   I can see a script to create the deployment request (https://github.com/jonico/pscale-workflow-helper-scripts/blob/main/.pscale/cli-helper-scripts/ps-create-helper-functions.sh) and to merge the deployment (https://github.com/jonico/pscale-workflow-helper-scripts/blob/main/.pscale/cli-helper-scripts/merge-deploy-request.sh)

Kind Regards
Alym Karim
________________________________

Alym Karim
Frontend Developer
+44 330 056 3100
 www.openstudycollege.com
Open Study College, 1760 Solihull Parkway,
 Birmingham Business Park, Birmingham. B37 7YD.
