### ISSUE TITLE
database list command only returns first 100 databases

### ISSUE THREAD

**Issue by joemiller** [planetscale/cli#564]
If an org has >100 databases only the first 100 will be returned with `pscale database list`.

**Comment by aquarapid** [comment]
This has been fixed by adding pagination;  there is a `--page` option now.

I did notice however, that there is also a new `--per-page` option, with the help saying:

```
--per-page int   Number of results per page (default 100)
```

This seems to be inaccurate however, it seems like the max returned is 100, even if you pass, for example, `200` in for this flag?  So I guess the help should say:  `(default 100, maximum 100)`?

**Comment by iheanyi** [comment]
@aquarapid It's a limitation of the framework we're using for the CLI. I will add validation that prevents the user from asking more than 100 databases

**Comment by iheanyi** [comment]
Okay, I'm closing this out given that this is done for now. For the validation on the `maximum`, I can follow-up on this separately, but with the pagination flags in place, this is done.
