### ISSUE TITLE
[Error] pscale auth login: decoding error response

### ISSUE THREAD

**Issue by BohengLiu** [planetscale/cli#595]
>  pscale auth login 
Error: decoding error response: invalid character '<' looking for beginning of value

**Comment by BohengLiu** [comment]
I have followed the guide of https://planetscale.com/docs/tutorials/automatic-prisma-migrations. But when i run the following command, i got an error.
>pscale auth login
pscale auth login

**Comment by BohengLiu** [comment]
Could anyone kindly help?

**Comment by BohengLiu** [comment]
the version is:  pscale version 0.125.0 (build date: 2022-12-13T15:43:16Z commit: 42da26c)

**Comment by johnyerhot** [comment]
Hey @BohengLiu, thanks for holding on.

There are regions where PlanetScale is not available and it looks like you may be connecting from one of those regions – the People's Republic of China. It also looks we haven't gracefully handled it in the CLI so you're getting the cryptic error.

We have updated our API backend to return a proper response now. You still will not be able to use PlanetScale from within the People's Republic of China, but you'll get an `access denied` instead of a non-specific error message.

**Comment by eastling** [comment]
I had the same error. how can i fix it
